AllCops:
  TargetRubyVersion: 2.3

Naming/PredicateName:
  # Method define macros for dynamically generated method.
  MethodDefinitionMacros:
    - define_method
    - define_singleton_method
    - def_node_matcher
    - def_node_search

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/GlobalVars:
  AllowedVariables: ['$trace_enabled', '$verbose_enabled']

Style/SignalException:
  Enabled: false

Metrics/LineLength:
  AllowHeredoc: true
  AllowURI: true
  Max: 220

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
      - module_inclusion
      - constants
      - public_class_methods
      - initializer
      - instance_methods
      - protected_methods
      - private_methods

Layout/IndentHeredoc:
  EnforcedStyle: powerpack

Layout/Tab:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/TrailingBlankLines:
  EnforcedStyle: final_newline

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
  AutoCorrect: true

Lint/BooleanSymbol:
  Enabled: false